name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@<commit-SHA>
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: sonnyquinn24
        numOfAssignee: 1
